### ISSUE TITLE
Kosár készítés

### ISSUE THREAD

**Issue by kardossziliva** [nagyjulcsi/pumpkinspice#3]
A Kosarat a Terméklista mellé helyeztük el, hogy a vásárlók könnyen megtalálják.
Terveink szerint a kosárba azok a termékek kerülnek amelyeket a leendő vásárlók a Terméklistáról kiválasztanak. (Add gomb kialakítására a későbbiekben kerül sor.)

A kosár lényege, hogy a terméklistáról kiválasztott termékeket összesítve, egymás alatt láthassuk.
A Kosárban lévő termékek mellett megjelenik hogy mennyibe kerülnek és hányat rendeltek belőle, így a vásárló pontosan nyomon tudja követni mit rendel,mennyit és mennyiért. (Későbbiekben kerül létrehozásra)

Ezt a részt azzal hangsúlyoztuk ki,hogy a többi részhez képest nagyobb betűméretet használtunk.
A dokumentáció végéhez a komment részben kerül csatolásra az elkészített kód.

**Comment by farkaskinga** [comment]
</div>
                            <div class="panel-body">
                                <span ng-if="cart.length == 0">A kosár üres</span>
                                <ul class="list-group">
                                    <li class="list-group-item" ng-repeat="cartItem in cart">
                                        {{ cartItem.name }}
                                        <span class="label label-info">HUF {{ cartItem.price }}</span>
                                        <span class="label label-default">{{ cartItem.amount }} db</span>
                                        <button class="btn btn-danger btn-xs pull-right" ng-click="removeItem(cartItem)">X</button>
                                    </li>
                                </ul>
                                <h3 class="pull-right" ng-class="{'red': sum() > 5000}">Összesen: HUF {{ sum() | number }}</h3>
                                
                                <form name="orderForm">
                                    <input name="name" ng-model="name" ng-required="true" ng-minlength="5"/>
                                    <button class="btn btn-primary" ng-disabled="!orderForm.$valid">Megrendel</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-sm-7 col-sm-pull-5">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
