### ISSUE TITLE
Kosártartalom összeadás

### ISSUE THREAD

**Issue by kbernadett** [nagyjulcsi/pumpkinspice#5]
Ebben a fejezetben a kosár tartalmával foglalkozunk. Miután sikerült elérnünk az "Add" funkcióval, hogy a terméklistából ki tudjuk választani a termékeket, amelyek rendelkeznek árral, a következő megoldandó feladat az, hogy a kosár össze tudja adni több termék rendelése esetén az értékeket. Illetve természetesen egy termék esetén, a kiválasztottnak is mutassa az összegét. Ennek megvalósítására létrehoztuk a következő kódot:
$scope.sum = function(){
        var sum = 0;
        $scope.cart.forEach(function(cartItem, i) {
            sum += cartItem.amount * cartItem.price;
        });       
        return sum;
    };

Ezáltal egy újabb funkcióval bővítettük a weblapunkat, tehát mostantól mindenki számára látható a megrendelés összértéke, miután a termékek a kosárba kerültek.

**Comment by nagyjulcsi** [comment]
A tesztelés folyamán itt találtunk egy hibát. Ha az összes termék összegénél nagyobb végösszeg jön ki, akkor azt hibaként kezeli, ezáltal átvált pirosra az összesen rovat színe, tehát azt jelzi, hogy nem lehet megrendelni.
