### ISSUE TITLE
Tesztelés

### ISSUE THREAD

**Issue by nagyjulcsi** [nagyjulcsi/pumpkinspice#9]
Amikor már elkészültünk minden egyes funkcióval, jött az utolsó fázis azaz a tesztelés.   
Erre azért van szükség, hogy a szoftverben a meglévő hibákat az üzembe helyezés előtt megtaláljuk, hogy ezzel növeljük a termék minőségét és megbízhatóságát.
Mivel többen készítettük el a szoftvert, bátran állíthatjuk, hogy vannak benne  hibák, amiket próbáltunk kijavítani, viszont nem lehetett mindent kiküszöbölni, így némi fennakadás lesz a program működése során                     
Minden egyes funkciót kipróbáltunk, hogy megfelelően működik-e, illetve ha valami hibát észleltünk a működés folyamán, azt megpróbáltuk orvosolni.   
Alkalmazásunk tesztelését a követelményspecifikáció alapján kezdtük el. Az itt felállított követelményeket vizsgáltuk meg, hogy programunk megfelelően tudja-e működtetni az adott funkciót.
A tesztelést a szoftver korai szakaszában elkezdtük, mivel minél hamarabb teszteltünk, annál könnyebben bukkanhatunk rá az esetlegesen felmerülő szélsőséges hibákra, illetve a kijavítás is egyszerűbb még a kezdeti szakaszban. Mivel a programunk mindig bővül, a tesztelések is folyamatos bővítéseket igényelnek, melyeket a felhasználói igényekre alapozva hoztunk létre.
A tesztelés szintjei közül a komponensteszttel kezdtünk, ezen belül is az egységteszttel, amely azt vizsgálja, hogy a tényleges visszatérési érték  megegyezik-e az elvárttal.
Végső teszteléskor a rendszerteszt módszerét alkalmaztuk, mikor már nem kívánunk további funkciókat hozzáadni programunkhoz. 
A talált hibák többségét mint már említettem kijavítottuk, de sajnos voltak olyanok amiket nem tudtunk megfelelően kijavítani, így részben nőtt a program megbízhatósága, minősége és kezelhetősége.

A következő problémák merültek fel a tesztelés során:
 - a termékek nem abc sorrendben vannak
 - az alkalmazás nem tud keresni ár alapján
 - a kosár tartalmát nem tudjuk megrendelni

**Comment by farkaskinga** [comment]
További észlelt probléma, hiba:  Ha a terméklistából egy termékből többet szereténk, azt annyiszor adja hozzá a kosárhoz ahányszor szeretnénk, azonban ha törölni akarunk a kosárból, akkor az adott termékből az összeset kitörli, nem pedig egyesével.
